server.port=9090

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

jwt.secret=93lOHo1gyQYk8uQmYYnbnw/GwY7LaKru997wX2jwPNrdGhlSxdjKRxOfGiG4aVBDY00Ru/2DM1YFoklBpoe/hQ==
jwt.expiration=86400000